-- Notification persistence table
-- Stores personal alerts for users who may not be connected via WebSocket

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    type       VARCHAR(50)                             NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    message    TEXT                                    NOT NULL,
    is_read    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ                             NOT NULL DEFAULT NOW(),
    version    BIGINT                                  NOT NULL DEFAULT 0,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

-- Index for paginated user notification history (ORDER BY created_at DESC)
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);

-- Partial index for efficient unread count queries
CREATE INDEX idx_notifications_user_unread ON notifications (user_id) WHERE is_read = FALSE;

-- Index for item-based cleanup when auction ends
CREATE INDEX idx_notifications_item ON notifications (item_id);
