-- V2: Create auth_credentials table
-- Supports multiple auth methods per user (LOCAL, GOOGLE, GITHUB)
-- Enables "Link with Google" / "Link with GitHub" features

CREATE TABLE auth_credentials (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    provider      VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255),
    provider_id   VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_provider CHECK (provider IN ('LOCAL', 'GOOGLE', 'GITHUB')),
    CONSTRAINT uq_provider_id UNIQUE (provider, provider_id)
);

-- Index for user's credentials lookup
CREATE INDEX idx_auth_credentials_user ON auth_credentials (user_id);

-- Index for OAuth provider lookups (find user by Google/GitHub ID)
CREATE INDEX idx_auth_credentials_provider ON auth_credentials (provider, provider_id);

COMMENT ON TABLE auth_credentials IS 'Authentication credentials supporting multiple auth methods per user';
COMMENT ON COLUMN auth_credentials.provider IS 'Auth method: LOCAL (email/password), GOOGLE (OAuth2), GITHUB (OAuth2)';
COMMENT ON COLUMN auth_credentials.password_hash IS 'BCrypt-hashed password, only for LOCAL provider';
COMMENT ON COLUMN auth_credentials.provider_id IS 'External provider user ID, only for OAuth providers';
