-- V3: Create refresh_tokens table
-- Hashed refresh tokens with token family for rotation detection
-- Token Family Pattern: All tokens in a rotation chain share the same family UUID
-- If a revoked token is reused (theft detected), the entire family is revoked

CREATE TABLE refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id     UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    token_hash   VARCHAR(255) NOT NULL,
    token_family VARCHAR(36) NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked      BOOLEAN NOT NULL DEFAULT FALSE
);

-- Index for O(1) token lookup by token_id (primary lookup mechanism)
CREATE INDEX idx_refresh_tokens_token_id ON refresh_tokens (token_id);

-- Index for finding active tokens by user (exclude revoked)
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id) WHERE revoked = FALSE;

-- Index for token family lookups (revoke entire family on theft detection)
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (token_family);

-- Index for cleanup job (find expired tokens)
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at) WHERE revoked = FALSE;

COMMENT ON TABLE refresh_tokens IS 'BCrypt-hashed refresh tokens with rotation detection via token families';
COMMENT ON COLUMN refresh_tokens.token_id IS 'Public lookup ID sent with refresh requests - enables O(1) DB lookup before BCrypt validation';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'BCrypt hash of the refresh token - raw token only known to client';
COMMENT ON COLUMN refresh_tokens.token_family IS 'UUID grouping tokens in a rotation chain for theft detection';
COMMENT ON COLUMN refresh_tokens.revoked IS 'Set TRUE when token is refreshed or user logs out';
