CREATE TABLE bids
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    bidder_id  UUID                                    NOT NULL,
    bid_amount DECIMAL(10, 2)                          NOT NULL,
    timestamp  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    version    BIGINT,
    CONSTRAINT pk_bids PRIMARY KEY (id)
);

CREATE INDEX idx_bidder ON bids (bidder_id);

CREATE INDEX idx_item_bid ON bids (item_id, bid_amount DESC);

CREATE INDEX idx_timestamp ON bids (timestamp DESC);