CREATE TABLE items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seller_id      UUID                                    NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    TEXT,
    starting_price DECIMAL(10, 2)                          NOT NULL,
    current_price  DECIMAL(10, 2)                          NOT NULL,
    image_url      VARCHAR(500),
    status         VARCHAR(255)                            NOT NULL,
    start_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE INDEX idx_seller_id ON items (seller_id);

CREATE INDEX idx_status_endtime ON items (status, end_time);