CREATE TABLE categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE item_categories
(
    category_id INTEGER NOT NULL,
    item_id     BIGINT  NOT NULL,
    CONSTRAINT pk_item_categories PRIMARY KEY (category_id, item_id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE item_categories
    ADD CONSTRAINT fk_itecat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE item_categories
    ADD CONSTRAINT fk_itecat_on_item FOREIGN KEY (item_id) REFERENCES items (id);